# vim: filetype=sh

# osx
if [[ $OSTYPE == darwin* ]]; then
  alias d="ls -FGO"
  alias ls="ls -FGO"
else
  alias d='ls -FG'
  alias ls='ls -FG'
fi

gzipchk() {
    curl -s -L -I -H 'Accept-Encoding: gzip,deflate' "$@" | grep --color "Content-Encoding"
}

alias pyclean='find . -type d -name "__pycache__" -print0 | xargs -0 rm -rf'
alias quxfind='find . -type f -name "$1" -print0 | xargs -0 grep $2'

# python shortcuts
alias profile="python -m cProfile"

if [ -f macosx.sh ]; then
  echo "Loading macosx.sh"
  source macosx.sh
fi