---
- hosts: servers
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
    - name: Install list of packages
      apt:
        pkg:
        - software-properties-common
        - landscape-common
        - update-notifier-common
        - cron
        - ufw
        - mailutils
        - postfix
        - tree
        - apache2
        - certbot
        - libsasl2-2
        - libsasl2-modules
        - libssl-dev
        - libffi-dev
        - liblapack-dev
        - gfortran
        - letsencrypt
        - python3
        - python3-dev
        - python3-pip
        - python3-venv
        - python3-virtualenv
        - python3-mysqldb
        - python3-scipy
        - python3-numpy
        - python3-pandas
        - python3-ipython
        - memcached
        - libapache2-mod-wsgi-py3
        - mysql-server
        - libmysqlclient-dev
        - python3-mysql.connector
        - python-celery-common
        - supervisor
        - redis
    - name: Update all packages
      apt:
        upgrade: dist
    - name: apt autoclean
      apt:
        autoclean: yes
    - name: apt autoremove
      apt:
        autoremove: yes
    - name: Add apt-get key from url
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
    - name: Copy options-ssl-apache.conf => /etc/letsencrypt/
      copy:
        src: ../files/options-ssl-apache.conf
        dest: /etc/letsencrypt/
    - name: Enable wsgi
      apache2_module:
        state: present
        name: wsgi
    - name: Enable ssl
      apache2_module:
        state: present
        name: ssl
    - name: Add user 'vishal'
      user:
        name: vishal
...
